
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Val
 */
public class Register extends javax.swing.JFrame {
    java.sql.Connection conn = null;
    ResultSet rs = null;
    Statement st=null;
    
int pressed_X;
int pressed_Y;

    /**
     * Creates new form Register
     */
    public Register() {
        
        initComponents();
        this.setLocationRelativeTo(null);
         password_eye.setEnabled(false);
         firstName_error.setVisible(false);
         lastName_error.setVisible(false);
         username_error.setVisible(false);
         password_error.setVisible(false);
         Login.setVisible(false);
         password_eye_login.setEnabled(false);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Registration = new javax.swing.JPanel();
        register_text = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        line_between = new javax.swing.JPanel();
        login_text = new javax.swing.JLabel();
        firstName_text = new javax.swing.JLabel();
        input_firstName = new javax.swing.JTextField();
        lastName_text = new javax.swing.JLabel();
        input_lastName = new javax.swing.JTextField();
        username_text = new javax.swing.JLabel();
        input_username = new javax.swing.JTextField();
        password_text = new javax.swing.JLabel();
        register_button = new javax.swing.JButton();
        input_password = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password_eye = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        seperator1 = new javax.swing.JPanel();
        seperator2 = new javax.swing.JPanel();
        seperator3 = new javax.swing.JPanel();
        seperator4 = new javax.swing.JPanel();
        firstName_error = new javax.swing.JLabel();
        lastName_error = new javax.swing.JLabel();
        username_error = new javax.swing.JLabel();
        password_error = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        seperator6 = new javax.swing.JPanel();
        seperator7 = new javax.swing.JPanel();
        register_text1 = new javax.swing.JLabel();
        line_between1 = new javax.swing.JPanel();
        login_text1 = new javax.swing.JLabel();
        username_text1 = new javax.swing.JLabel();
        input_username_login = new javax.swing.JTextField();
        password_text1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        input_password_login = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password_eye_login = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(550, 250));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));

        jLayeredPane1.setBackground(new java.awt.Color(28, 32, 37));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(651, 623));

        Registration.setBackground(new java.awt.Color(28, 32, 37));
        Registration.setForeground(new java.awt.Color(60, 63, 65));
        Registration.setPreferredSize(new java.awt.Dimension(651, 623));

        register_text.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        register_text.setForeground(new java.awt.Color(49, 130, 233));
        register_text.setText("Register");
        register_text.setToolTipText("");
        register_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_text.setPreferredSize(new java.awt.Dimension(90, 50));

        line_between.setBackground(new java.awt.Color(255, 255, 255));
        line_between.setPreferredSize(new java.awt.Dimension(3, 49));

        javax.swing.GroupLayout line_betweenLayout = new javax.swing.GroupLayout(line_between);
        line_between.setLayout(line_betweenLayout);
        line_betweenLayout.setHorizontalGroup(
            line_betweenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        line_betweenLayout.setVerticalGroup(
            line_betweenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        login_text.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        login_text.setForeground(new java.awt.Color(49, 130, 233));
        login_text.setText("Log in");
        login_text.setToolTipText("");
        login_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_text.setPreferredSize(new java.awt.Dimension(90, 50));
        login_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_textMouseClicked(evt);
            }
        });

        firstName_text.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        firstName_text.setForeground(new java.awt.Color(255, 255, 255));
        firstName_text.setText("First Name");

        input_firstName.setBackground(new java.awt.Color(28, 32, 37));
        input_firstName.setForeground(new java.awt.Color(153, 153, 153));
        input_firstName.setText("Your First Name");
        input_firstName.setBorder(null);
        input_firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_firstNameFocusLost(evt);
            }
        });
        input_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_firstNameActionPerformed(evt);
            }
        });
        input_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_firstNameKeyTyped(evt);
            }
        });

        lastName_text.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lastName_text.setForeground(new java.awt.Color(255, 255, 255));
        lastName_text.setText("Last Name");

        input_lastName.setBackground(new java.awt.Color(28, 32, 37));
        input_lastName.setForeground(new java.awt.Color(153, 153, 153));
        input_lastName.setText("Your Last Name");
        input_lastName.setBorder(null);
        input_lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_lastNameFocusLost(evt);
            }
        });
        input_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_lastNameActionPerformed(evt);
            }
        });
        input_lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_lastNameKeyTyped(evt);
            }
        });

        username_text.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        username_text.setForeground(new java.awt.Color(255, 255, 255));
        username_text.setText("Username");

        input_username.setBackground(new java.awt.Color(28, 32, 37));
        input_username.setForeground(new java.awt.Color(153, 153, 153));
        input_username.setText("Your Desired Username");
        input_username.setBorder(null);
        input_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_usernameFocusLost(evt);
            }
        });
        input_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_usernameActionPerformed(evt);
            }
        });
        input_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_usernameKeyTyped(evt);
            }
        });

        password_text.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        password_text.setForeground(new java.awt.Color(255, 255, 255));
        password_text.setText("Password");

        register_button.setBackground(new java.awt.Color(28, 32, 37));
        register_button.setForeground(new java.awt.Color(20, 167, 223));
        register_button.setText("Register");
        register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_buttonMouseClicked(evt);
            }
        });
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });
        register_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                register_buttonKeyReleased(evt);
            }
        });

        input_password.setBackground(new java.awt.Color(28, 32, 37));
        input_password.setForeground(new java.awt.Color(153, 153, 153));
        input_password.setText("********"); // NOI18N
        input_password.setBorder(null);
        input_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_passwordFocusLost(evt);
            }
        });
        input_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                input_passwordMouseEntered(evt);
            }
        });
        input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_passwordActionPerformed(evt);
            }
        });
        input_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_passwordKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(28, 32, 37));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 187, 192));
        jLabel1.setText("-");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 187, 192));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        password_eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_show_hide_password-07-512.png"))); // NOI18N
        password_eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        password_eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                password_eyeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                password_eyeMouseReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setForeground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        seperator1.setBackground(new java.awt.Color(108, 122, 137));
        seperator1.setForeground(new java.awt.Color(0, 204, 204));
        seperator1.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout seperator1Layout = new javax.swing.GroupLayout(seperator1);
        seperator1.setLayout(seperator1Layout);
        seperator1Layout.setHorizontalGroup(
            seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        seperator1Layout.setVerticalGroup(
            seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        seperator2.setBackground(new java.awt.Color(108, 122, 137));
        seperator2.setForeground(new java.awt.Color(0, 204, 204));
        seperator2.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout seperator2Layout = new javax.swing.GroupLayout(seperator2);
        seperator2.setLayout(seperator2Layout);
        seperator2Layout.setHorizontalGroup(
            seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        seperator2Layout.setVerticalGroup(
            seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        seperator3.setBackground(new java.awt.Color(108, 122, 137));
        seperator3.setForeground(new java.awt.Color(0, 204, 204));
        seperator3.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout seperator3Layout = new javax.swing.GroupLayout(seperator3);
        seperator3.setLayout(seperator3Layout);
        seperator3Layout.setHorizontalGroup(
            seperator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        seperator3Layout.setVerticalGroup(
            seperator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        seperator4.setBackground(new java.awt.Color(108, 122, 137));
        seperator4.setForeground(new java.awt.Color(0, 204, 204));
        seperator4.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout seperator4Layout = new javax.swing.GroupLayout(seperator4);
        seperator4.setLayout(seperator4Layout);
        seperator4Layout.setHorizontalGroup(
            seperator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        seperator4Layout.setVerticalGroup(
            seperator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        firstName_error.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        firstName_error.setForeground(new java.awt.Color(215, 43, 43));
        firstName_error.setText("The first name field should not have more than 25 characters.");

        lastName_error.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lastName_error.setForeground(new java.awt.Color(215, 43, 43));
        lastName_error.setText("The last name field should not have more than 25 characters.");

        username_error.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        username_error.setForeground(new java.awt.Color(215, 43, 43));
        username_error.setText("The username field should have between 3 and 25 characters.");

        password_error.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        password_error.setForeground(new java.awt.Color(215, 43, 43));
        password_error.setText("The password field should have between 8 and 25 characters.");

        javax.swing.GroupLayout RegistrationLayout = new javax.swing.GroupLayout(Registration);
        Registration.setLayout(RegistrationLayout);
        RegistrationLayout.setHorizontalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(password_eye, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationLayout.createSequentialGroup()
                                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(input_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstName_text)
                                            .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationLayout.createSequentialGroup()
                                        .addComponent(login_text, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(line_between, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(register_text, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(116, 116, 116)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(input_username, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addComponent(username_text)
                                .addGap(18, 18, 18)
                                .addComponent(username_error))
                            .addComponent(input_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addComponent(lastName_text)
                                .addGap(18, 18, 18)
                                .addComponent(lastName_error))
                            .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addComponent(password_text)
                                .addGap(18, 18, 18)
                                .addComponent(password_error))))
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationLayout.createSequentialGroup()
                                .addComponent(firstName_error, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addComponent(jLabel2)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        RegistrationLayout.setVerticalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(line_between, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(register_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(login_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstName_text)
                            .addComponent(firstName_error))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastName_text)
                            .addComponent(lastName_error))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(input_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_text)
                    .addComponent(username_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_text)
                    .addComponent(password_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_eye, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        Login.setBackground(new java.awt.Color(28, 32, 37));
        Login.setPreferredSize(new java.awt.Dimension(611, 582));

        seperator6.setBackground(new java.awt.Color(108, 122, 137));
        seperator6.setForeground(new java.awt.Color(0, 204, 204));
        seperator6.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout seperator6Layout = new javax.swing.GroupLayout(seperator6);
        seperator6.setLayout(seperator6Layout);
        seperator6Layout.setHorizontalGroup(
            seperator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        seperator6Layout.setVerticalGroup(
            seperator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        seperator7.setBackground(new java.awt.Color(108, 122, 137));
        seperator7.setForeground(new java.awt.Color(0, 204, 204));
        seperator7.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout seperator7Layout = new javax.swing.GroupLayout(seperator7);
        seperator7.setLayout(seperator7Layout);
        seperator7Layout.setHorizontalGroup(
            seperator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        seperator7Layout.setVerticalGroup(
            seperator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        register_text1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        register_text1.setForeground(new java.awt.Color(49, 130, 233));
        register_text1.setText("Register");
        register_text1.setToolTipText("");
        register_text1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_text1.setPreferredSize(new java.awt.Dimension(90, 50));
        register_text1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_text1MouseClicked(evt);
            }
        });

        line_between1.setBackground(new java.awt.Color(255, 255, 255));
        line_between1.setPreferredSize(new java.awt.Dimension(3, 49));
        line_between1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                line_between1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout line_between1Layout = new javax.swing.GroupLayout(line_between1);
        line_between1.setLayout(line_between1Layout);
        line_between1Layout.setHorizontalGroup(
            line_between1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        line_between1Layout.setVerticalGroup(
            line_between1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        login_text1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        login_text1.setForeground(new java.awt.Color(49, 130, 233));
        login_text1.setText("Log in");
        login_text1.setToolTipText("");
        login_text1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_text1.setPreferredSize(new java.awt.Dimension(90, 50));

        username_text1.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        username_text1.setForeground(new java.awt.Color(255, 255, 255));
        username_text1.setText("Username");

        input_username_login.setBackground(new java.awt.Color(28, 32, 37));
        input_username_login.setForeground(new java.awt.Color(153, 153, 153));
        input_username_login.setText("Your Username");
        input_username_login.setBorder(null);
        input_username_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_username_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_username_loginFocusLost(evt);
            }
        });
        input_username_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_username_loginActionPerformed(evt);
            }
        });
        input_username_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_username_loginKeyTyped(evt);
            }
        });

        password_text1.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        password_text1.setForeground(new java.awt.Color(255, 255, 255));
        password_text1.setText("Password");

        jButton2.setBackground(new java.awt.Color(28, 32, 37));
        jButton2.setForeground(new java.awt.Color(20, 167, 223));
        jButton2.setText("Log in");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        input_password_login.setBackground(new java.awt.Color(28, 32, 37));
        input_password_login.setForeground(new java.awt.Color(153, 153, 153));
        input_password_login.setText("********"); // NOI18N
        input_password_login.setBorder(null);
        input_password_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_password_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_password_loginFocusLost(evt);
            }
        });
        input_password_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                input_password_loginMouseEntered(evt);
            }
        });
        input_password_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_password_loginActionPerformed(evt);
            }
        });
        input_password_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_password_loginKeyTyped(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(28, 32, 37));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(174, 187, 192));
        jLabel3.setText("-");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(174, 187, 192));
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        password_eye_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_show_hide_password-07-512.png"))); // NOI18N
        password_eye_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        password_eye_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                password_eye_loginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                password_eye_loginMouseReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setForeground(new java.awt.Color(0, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(75, 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(password_eye_login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seperator6, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_text1)
                                    .addComponent(input_username_login, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_password_login, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seperator7, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username_text1)))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginLayout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(login_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(line_between1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(register_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LoginLayout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(username_text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_username_login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password_text1)
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_eye_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_password_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(line_between1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LoginLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(register_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(login_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(476, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Registration, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(Registration, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Login, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_eyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_eyeMouseReleased
        input_password.setEchoChar('*');
    }//GEN-LAST:event_password_eyeMouseReleased

    private void password_eyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_eyeMousePressed
        input_password.setEchoChar((char)0);
    }//GEN-LAST:event_password_eyeMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setState(Register.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        pressed_X=evt.getX();
        pressed_Y=evt.getY();

    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int coordinates_X=evt.getXOnScreen();
        int coordinates_Y=evt.getYOnScreen();
        this.setLocation(coordinates_X-pressed_X,coordinates_Y-pressed_Y);
        
    }//GEN-LAST:event_jPanel2MouseDragged

    private void input_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_passwordKeyTyped
        password_eye.setEnabled(true);
    }//GEN-LAST:event_input_passwordKeyTyped

    private void input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordActionPerformed

    private void input_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_passwordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordMouseEntered

    private void input_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_passwordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordFocusLost

    private void input_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_passwordFocusGained
        if (input_password.getText().equals("********"))
        input_password.setText("");
    }//GEN-LAST:event_input_passwordFocusGained

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_buttonActionPerformed

    
      public boolean checkUsername(String username){
         boolean  username_exist = false;
         String current=System.getProperty("user.dir");
           try{
        conn=DriverManager.getConnection("jdbc:derby:"+current+"/Users","admin123","admin");
        st = (Statement) conn.createStatement();
        rs=st.executeQuery("SELECT USERNAME, PASSWORD FROM Users");
        while(rs.next()){
        if(rs.getString(1).equals(username)){
         JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
         username_exist=true;
        }
           }    
        }catch(SQLException SQLExcept){
        JOptionPane.showMessageDialog(null, "Connection failed","Registration System", JOptionPane.ERROR_MESSAGE);
            System.out.println(""+SQLExcept);

        }
           return username_exist;
      }
    private void register_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseClicked
        String firstName=input_firstName.getText();
        String lastName=input_lastName.getText();
        String username=input_username.getText();
        String password=input_password.getText();
        firstName_error.setVisible(false);
        lastName_error.setVisible(false);
        username_error.setVisible(false);
        password_error.setVisible(false);
        firstName_text.setForeground(Color.WHITE);
        lastName_text.setForeground(Color.WHITE);
        username_text.setForeground(Color.WHITE);
        password_text.setForeground(Color.WHITE);
        seperator1.setBackground(Color.GRAY);
        seperator2.setBackground(Color.GRAY);
        seperator3.setBackground(Color.GRAY);
        seperator4.setBackground(Color.GRAY);
        
        boolean correct=true;
        if (firstName.length()>25||firstName.equals("Your First Name")) {
            seperator1.setBackground(Color.red);
            firstName_text.setForeground(Color.red);
            firstName_error.setVisible(true);
            correct=false;
        }

        if (lastName.length()>25||lastName.equals("Your Last Name")) {
            seperator2.setBackground(Color.red);
            lastName_text.setForeground(Color.red);
            lastName_error.setVisible(true);
            correct=false;
        }

        if (username.length()<3||username.length()>25||username.equals("Your Desired Username")) {
            seperator3.setBackground(Color.red);
            username_text.setForeground(Color.red);
            username_error.setVisible(true);
            correct=false;
        }

        if (password.length()<8||password.length()>25||password.equals("********")) {
            seperator4.setBackground(Color.red);
            password_text.setForeground(Color.red);
            password_error.setVisible(true);
            correct=false;
        }
        if (!checkUsername(username)&&correct==true) {
        String current =System.getProperty("user.dir");
        try{
            Connection con=DriverManager.getConnection("jdbc:derby:"+current+"/Users","admin123","admin");
            PreparedStatement st1=con.prepareStatement("INSERT INTO Users (name, surname,username,password) VALUES (?,?,?,?)");
            
        st1.setString(1, firstName);
        st1.setString(2, lastName);
        st1.setString(3, username);
        st1.setString(4, password);
        int a=st1.executeUpdate();
            if (a>0) JOptionPane.showMessageDialog(null, "Your account has been successfully created","Registration System",JOptionPane.INFORMATION_MESSAGE);
            
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Connection failed","Registration System", JOptionPane.ERROR_MESSAGE);
            System.out.println(""+ex);
        }
    }
        
    }//GEN-LAST:event_register_buttonMouseClicked

    private void input_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_usernameKeyTyped
       
    }//GEN-LAST:event_input_usernameKeyTyped

    private void input_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_usernameActionPerformed

    private void input_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_usernameFocusLost
        if (input_username.getText().equals(""))
        input_username.setText("Your Desired Username");
    }//GEN-LAST:event_input_usernameFocusLost

    private void input_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_usernameFocusGained
        if (input_username.getText().equals("Your Desired Username"))
        input_username.setText("");
    }//GEN-LAST:event_input_usernameFocusGained

    private void input_lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_lastNameKeyTyped
        char key=evt.getKeyChar();
        if (Character.isLetter(key)||Character.isWhitespace(key)||Character.isISOControl(key))
        input_lastName.setEditable(true);
        else
        input_lastName.setEditable(false);
    }//GEN-LAST:event_input_lastNameKeyTyped

    private void input_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_lastNameActionPerformed

    private void input_lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_lastNameFocusLost
        if (input_lastName.getText().equals("")) {
            input_lastName.setText("Your Last Name");
        }
    }//GEN-LAST:event_input_lastNameFocusLost

    private void input_lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_lastNameFocusGained
        if (input_lastName.getText().equals("Your Last Name"))
        input_lastName.setText("");
    }//GEN-LAST:event_input_lastNameFocusGained

    private void input_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_firstNameKeyTyped
        char key=evt.getKeyChar();     
        if (Character.isLetter(key)||Character.isWhitespace(key)||Character.isISOControl(key))
        input_firstName.setEditable(true);
        else
        input_firstName.setEditable(false);
    }//GEN-LAST:event_input_firstNameKeyTyped

    private void input_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_firstNameActionPerformed

    private void input_firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_firstNameFocusLost
        if (input_firstName.getText().equals(""))
        input_firstName.setText("Your First Name");
    }//GEN-LAST:event_input_firstNameFocusLost

    private void input_firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_firstNameFocusGained
        if (input_firstName.getText().equals("Your First Name"))
        input_firstName.setText("");
    }//GEN-LAST:event_input_firstNameFocusGained

    private void input_username_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_username_loginFocusGained
         if (input_username_login.getText().equals("Your Username"))
        input_username_login.setText("");
    }//GEN-LAST:event_input_username_loginFocusGained

    private void input_username_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_username_loginFocusLost
       if (input_username_login.getText().equals(""))
        input_username_login.setText("Your Username");
    }//GEN-LAST:event_input_username_loginFocusLost

    private void input_username_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_username_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_username_loginActionPerformed

    private void input_username_loginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_username_loginKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_input_username_loginKeyTyped

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       //login connection
        
        String username = input_username_login.getText();
        String password = input_password_login.getText();
        boolean logged=false;
        String current =System.getProperty("user.dir");
        try{
        conn=DriverManager.getConnection("jdbc:derby:"+current+"/Users","admin123","admin");
        st = (Statement) conn.createStatement();
        rs=st.executeQuery("SELECT * FROM Users");
        while(rs.next()){
        if(rs.getString(3).equals(username)&&rs.getString(4).equals(password)){
            String name=rs.getString(1);
          String surname=rs.getString(2);
            logged=true;
        Welcome welcome=new Welcome(name,surname);
        welcome.setVisible(true);
        welcome.setLocationRelativeTo(this);
        this.dispose();
        break;
        }
           
     }  
            if (!logged) {
                JOptionPane.showMessageDialog(null, "Incorrect username or password","Log in error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(SQLException SQLExcept){
        JOptionPane.showMessageDialog(null, "Connection failed","Login System", JOptionPane.ERROR_MESSAGE);
            System.out.println(""+SQLExcept);
        }    
       
                
           
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input_password_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_password_loginFocusGained
       if (input_password_login.getText().equals("********"))
        input_password_login.setText("");
    }//GEN-LAST:event_input_password_loginFocusGained

    private void input_password_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_password_loginFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_input_password_loginFocusLost

    private void input_password_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_password_loginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_input_password_loginMouseEntered

    private void input_password_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_password_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_password_loginActionPerformed

    private void input_password_loginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_password_loginKeyTyped
        password_eye_login.setEnabled(true);
    }//GEN-LAST:event_input_password_loginKeyTyped

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int coordinates_X=evt.getXOnScreen();
        int coordinates_Y=evt.getYOnScreen();
        this.setLocation(coordinates_X-pressed_X,coordinates_Y-pressed_Y);
       
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
       pressed_X=evt.getX();
        pressed_Y=evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(Register.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void password_eye_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_eye_loginMousePressed
        input_password_login.setEchoChar((char)0);
    }//GEN-LAST:event_password_eye_loginMousePressed

    private void password_eye_loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_eye_loginMouseReleased
        input_password_login.setEchoChar('*');
    }//GEN-LAST:event_password_eye_loginMouseReleased

    private void login_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_textMouseClicked
        Registration.setVisible(false);
        Login.setVisible(true);
        input_firstName.setText("Your First Name");
        input_lastName.setText("Your Last Name");
        input_username.setText("Your Desired Username");
        input_password.setText("********");
        password_eye.setEnabled(false);
        firstName_error.setVisible(false);
        lastName_error.setVisible(false);
        username_error.setVisible(false);
        password_error.setVisible(false);
        firstName_text.setForeground(Color.WHITE);
        lastName_text.setForeground(Color.WHITE);
        username_text.setForeground(Color.WHITE);
        password_text.setForeground(Color.WHITE);
        seperator1.setBackground(Color.GRAY);
        seperator2.setBackground(Color.GRAY);
        seperator3.setBackground(Color.GRAY);
        seperator4.setBackground(Color.GRAY);
    }//GEN-LAST:event_login_textMouseClicked

    private void register_text1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_text1MouseClicked
        Login.setVisible(false);
        Registration.setVisible(true);
     input_username_login.setText("Your Username");
     input_password_login.setText("********");
     password_eye_login.setEnabled(false);
     
    }//GEN-LAST:event_register_text1MouseClicked

    private void line_between1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_line_between1MouseClicked
        
    }//GEN-LAST:event_line_between1MouseClicked

    private void register_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_register_buttonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_register_buttonKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Registration;
    private javax.swing.JLabel firstName_error;
    private javax.swing.JLabel firstName_text;
    private javax.swing.JTextField input_firstName;
    private javax.swing.JTextField input_lastName;
    private javax.swing.JPasswordField input_password;
    private javax.swing.JPasswordField input_password_login;
    private javax.swing.JTextField input_username;
    private javax.swing.JTextField input_username_login;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastName_error;
    private javax.swing.JLabel lastName_text;
    private javax.swing.JPanel line_between;
    private javax.swing.JPanel line_between1;
    private javax.swing.JLabel login_text;
    private javax.swing.JLabel login_text1;
    private javax.swing.JLabel password_error;
    private javax.swing.JLabel password_eye;
    private javax.swing.JLabel password_eye_login;
    private javax.swing.JLabel password_text;
    private javax.swing.JLabel password_text1;
    private javax.swing.JButton register_button;
    private javax.swing.JLabel register_text;
    private javax.swing.JLabel register_text1;
    private javax.swing.JPanel seperator1;
    private javax.swing.JPanel seperator2;
    private javax.swing.JPanel seperator3;
    private javax.swing.JPanel seperator4;
    private javax.swing.JPanel seperator6;
    private javax.swing.JPanel seperator7;
    private javax.swing.JLabel username_error;
    private javax.swing.JLabel username_text;
    private javax.swing.JLabel username_text1;
    // End of variables declaration//GEN-END:variables
}
